# Generated by Django 5.1.4 on 2025-01-22 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The headline of the blog post.', max_length=200, verbose_name='Title')),
                ('short_description', models.TextField(help_text='A teaser or brief description of the blog post.', verbose_name='Short Description')),
                ('content', models.TextField(help_text='The full content of the blog post, including text, images, videos, and other media.', verbose_name='Content')),
                ('category', models.CharField(choices=[('tech_news', 'Tech News'), ('how_to_guides', 'How-To Guides'), ('other', 'Other')], help_text='The blog category to help organize posts.', max_length=50, verbose_name='Category')),
                ('tags', models.CharField(help_text='Keywords or phrases associated with the blog post.', max_length=200, verbose_name='Tags')),
                ('featured_image', models.ImageField(help_text='The image that will appear at the top of the blog post or as a thumbnail.', upload_to='blog_images/', verbose_name='Featured Image')),
                ('date_published', models.DateTimeField(help_text='The publication date of the blog post.', verbose_name='Date Published')),
                ('is_active', models.BooleanField(default=True, help_text='A boolean field to indicate if the blog post is currently live.', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'ordering': ['-date_published'],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Job title', max_length=255)),
                ('department', models.CharField(help_text='Department', max_length=255)),
                ('job_location', models.CharField(help_text='Office location or remote', max_length=255)),
                ('job_description', models.TextField(blank=True, help_text='Job role, responsibilities, and requirements', null=True)),
                ('qualifications', models.TextField(blank=True, help_text='Skills, experience, and education required', null=True)),
                ('application_link', models.URLField(blank=True, help_text='Link to apply for the job', max_length=500, null=True)),
                ('application_instructions', models.TextField(blank=True, help_text='How to submit an application if no link is provided', null=True)),
                ('active', models.BooleanField(default=True, help_text='Is the job listing active?')),
                ('date_posted', models.DateField(auto_now_add=True, help_text='Date posted')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='NewsArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The headline or title of the news article.', max_length=200, verbose_name='Title')),
                ('short_description', models.TextField(help_text='A brief summary of the news article.', verbose_name='Short Description')),
                ('full_content', models.TextField(help_text='The body of the news article, which can include text, images, and videos.', verbose_name='Full Content')),
                ('category', models.CharField(choices=[('product_launch', 'Product Launch'), ('industry_update', 'Industry Update'), ('other', 'Other')], help_text='Category or type of news.', max_length=50, verbose_name='Category')),
                ('date_published', models.DateTimeField(help_text='The publication date of the news article.', verbose_name='Date Published')),
                ('is_active', models.BooleanField(default=True, help_text='A boolean field to specify if the news is active (visible on the website).', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'News Article',
                'verbose_name_plural': 'News Articles',
                'ordering': ['-date_published'],
            },
        ),
    ]
