# Generated by Django 5.1.4 on 2025-01-15 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='participant_age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='participant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='participant_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='participant_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
