# Generated by Django 5.1.4 on 2025-01-24 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, help_text='The name of the blog post author.', max_length=255, null=True, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='The icon image representing the news article, shown as a thumbnail or preview image.', null=True, upload_to='news_icons/', verbose_name='News Icon'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('business_achievements', 'Business Achievements'), ('tech_news', 'Tech News'), ('how_to_guides', 'How-To Guides'), ('other', 'Other')], help_text='The blog category to help organize posts.', max_length=50, verbose_name='Category'),
        ),
    ]
