# Generated by Django 5.1.4 on 2025-02-24 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quoterequest',
            name='product',
        ),
    ]
