# Generated by Django 5.1.4 on 2024-12-31 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_blogpost_created_at_blogpost_deleted_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(help_text='Job title', max_length=255)),
                ('department', models.CharField(help_text='Department', max_length=255)),
                ('job_location', models.CharField(help_text='Office location or remote', max_length=255)),
                ('job_description', models.TextField(blank=True, help_text='Job role, responsibilities, and requirements', null=True)),
                ('qualifications', models.TextField(blank=True, help_text='Skills, experience, and education required', null=True)),
                ('application_link', models.URLField(blank=True, help_text='Link to apply for the job', max_length=500, null=True)),
                ('application_instructions', models.TextField(blank=True, help_text='How to submit an application if no link is provided', null=True)),
                ('active', models.BooleanField(default=True, help_text='Is the job listing active?')),
                ('date_posted', models.DateField(auto_now_add=True, help_text='Date posted')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
