# Generated by Django 5.1.4 on 2025-02-20 07:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_customerserviceenquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=100)),
                ('product_name', models.CharField(max_length=200)),
                ('question', models.TextField()),
                ('attachment', models.FileField(blank=True, upload_to='question_attachments/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'doc', 'docx', 'jpg', 'jpeg', 'png'])])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('answered', 'Answered'), ('closed', 'Closed')], default='pending', max_length=20)),
            ],
            options={
                'verbose_name': 'Question Submission',
                'verbose_name_plural': 'Question Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
