# Generated by Django 5.1.4 on 2025-01-20 07:12

import admin_dashboard.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_alter_newsarticle_full_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=admin_dashboard.fields.CustomSummernoteTextField(blank=True, help_text='The full content of the blog post, including text, images, videos, and other media.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=admin_dashboard.fields.CustomSummernoteTextField(blank=True, help_text='A teaser or brief description of the blog post.', null=True, verbose_name='Short Description'),
        ),
    ]
