# Generated by Django 5.1.4 on 2025-03-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_oldurlredirect'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OldUrlRedirect',
        ),
    ]
