# Generated by Django 5.1.4 on 2025-01-21 05:21

import admin_dashboard.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_alter_blogpost_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='job_description',
            field=admin_dashboard.fields.CustomSummernoteTextField(blank=True, help_text='Job role, responsibilities, and requirements', null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualifications',
            field=admin_dashboard.fields.CustomSummernoteTextField(blank=True, help_text='Skills, experience, and education required', null=True),
        ),
    ]
