# Generated by Django 5.1.4 on 2025-01-23 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_alter_joblisting_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='category',
            field=models.CharField(choices=[('business_achievements', 'Business Achievements'), ('tech_news', 'Tech News'), ('how_to_guides', 'How-To Guides'), ('other', 'Other')], help_text='The blog category to help organize posts.', max_length=50, verbose_name='Category'),
        ),
    ]
