# Generated by Django 5.1.4 on 2025-01-23 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_alter_blogpost_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='author',
            field=models.CharField(blank=True, help_text='The name of the blog post author.', max_length=255, null=True, verbose_name='Author'),
        ),
    ]
