# Generated by Django 5.1.4 on 2025-01-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0008_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='The icon image representing the news article, shown as a thumbnail or preview image.', null=True, upload_to='news_icons/', verbose_name='News Icon'),
        ),
    ]
