# Generated by Django 5.1.4 on 2025-02-04 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0009_newsarticle_featured_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='event_end_date',
            field=models.DateTimeField(blank=True, help_text='The end date of the event (required if this is an event news).', null=True, verbose_name='Event End Date'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='event_start_date',
            field=models.DateTimeField(blank=True, help_text='The start date of the event (required if this is an event news).', null=True, verbose_name='Event Start Date'),
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='is_event_news',
            field=models.BooleanField(default=False, help_text='If True, this news is related to an event.', verbose_name='Is Event News'),
        ),
    ]
