# Generated by Django 5.1.4 on 2025-02-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0015_contactsubmission_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(blank=True, help_text='The full content of the blog post, including text, images, videos, and other media.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='short_description',
            field=models.TextField(blank=True, help_text='A teaser or brief description of the blog post.', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='job_description',
            field=models.TextField(blank=True, help_text='Job role, responsibilities, and requirements', null=True),
        ),
        migrations.AlterField(
            model_name='joblisting',
            name='qualifications',
            field=models.TextField(blank=True, help_text='Skills, experience, and education required', null=True),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='full_content',
            field=models.TextField(blank=True, help_text='The body of the news article, which can include text, images, and videos.', null=True, verbose_name='Full Content'),
        ),
        migrations.AlterField(
            model_name='newsarticle',
            name='short_description',
            field=models.TextField(blank=True, help_text='A brief summary of the news article.', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='category',
            field=models.CharField(blank=True, choices=[('network_infrastructure', 'Network Infrastructure'), ('cybersecurity', 'Cybersecurity'), ('cloud_solutions', 'Cloud Solutions'), ('other', 'Other')], help_text='The category the project falls under.', max_length=50, null=True, verbose_name='Project Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(blank=True, help_text='Detailed information about the project, its objectives, scope, and significance.', null=True, verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='project',
            name='short_description',
            field=models.TextField(blank=True, help_text='A brief summary of the project.', null=True, verbose_name='Short Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('on_hold', 'On Hold')], default='ongoing', help_text='The current state of the project.', max_length=20, null=True, verbose_name='Project Status'),
        ),
    ]
