"""Add updated_at column to records

Revision ID: 88895fa0aaf4
Revises: 869f7395c33d
Create Date: 2025-03-14 17:18:57.821938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88895fa0aaf4'
down_revision = '869f7395c33d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('records', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
