# Generated by Django 5.1.4 on 2024-12-27 10:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_specification_heading_productspecification_specification_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Descriptive and concise product name', max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(2)]),
        ),
    ]
