# Generated by Django 5.1.4 on 2025-01-07 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='Category_id',
            field=models.PositiveIntegerField(blank=True, help_text='Custom auto-incremented ID', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
