# Generated by Django 5.1.4 on 2025-01-09 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_category_category_id_alter_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdocument',
            name='document_type',
            field=models.CharField(choices=[('manual', 'User Manual'), ('specification', 'Technical Specification'), ('brochure', 'Product Brochure'), ('other', 'Other Document')], default='Product Documentation', help_text='Classification of the document', max_length=50),
        ),
    ]
