# Generated by Django 5.1.4 on 2025-01-17 08:22

import catalog.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_alter_productdocument_document_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='detailed_description',
            field=catalog.fields.CustomSummernoteTextField(blank=True, help_text='Comprehensive description for SEO and context', null=True),
        ),
    ]
