# Generated by Django 5.1.4 on 2025-01-17 09:15

import catalog.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_alter_category_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='detailed_description',
            field=catalog.fields.CustomSummernoteTextField(blank=True, help_text='Detailed explanation including features and benefits', null=True),
        ),
    ]
