# Generated by Django 5.1.4 on 2025-02-07 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_alter_product_detailed_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Comprehensive description for SEO and context', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='detailed_description',
            field=models.TextField(blank=True, help_text='Detailed explanation including features and benefits', null=True),
        ),
    ]
